
"use strict";
var testUser=(new URLSearchParams(location.search).get("user")||"").trim().slice(0,24);
var KEY="revcord-state-v3:"+location.pathname+(testUser?":test:"+testUser.toLowerCase():"");
var MAX_MESSAGE_LENGTH=2000,MAX_MESSAGES_PER_CHANNEL=500,MAX_SERVERS=50,MAX_CHANNELS=50,MAX_FRIENDS=500,MAX_REQUESTS=500;
var base={username:"",activeServer:"home",activeChannel:"general",servers:[{id:"home",name:"Home",icon:"R",channels:[{id:"general",name:"general",type:"text"},{id:"off-topic",name:"off-topic",type:"text"},{id:"lounge",name:"Lounge",type:"voice"}]}],messages:{general:[{id:"welcome",user:"RevCord",text:"Welcome to RevCord. This is a local-only workspace until a backend is added.",time:Date.now()}],"off-topic":[]},friends:[],requests:[],settings:{theme:"dark",compact:false,animations:true,notifications:true,keybinds:true}};
var state=load(), channelBeforeCall=null, bc=null, pc=null, stream=null, peer=null, callToken=null, deafened=false, voiceRoom=null, voicePeers={}, voiceActive=false, incomingOffer=null, sessionId=uid("tab");if(testUser)state.username=testUser;
function validName(v,max){return typeof v==="string"&&v.trim().length>=2&&v.trim().length<=max}
function normalizeState(x){var y=JSON.parse(JSON.stringify(base));if(!x||typeof x!=="object")return y;if(validName(x.username,24))y.username=x.username.trim();if(typeof x.activeServer==="string")y.activeServer=x.activeServer.slice(0,100);if(typeof x.activeChannel==="string")y.activeChannel=x.activeChannel.slice(0,100);if(Array.isArray(x.servers)){y.servers=x.servers.filter(function(s){return s&&typeof s==="object"&&typeof s.id==="string"&&validName(s.name,30)&&Array.isArray(s.channels)}).slice(0,MAX_SERVERS).map(function(s){return {id:s.id.slice(0,100),name:s.name.trim().slice(0,30),icon:typeof s.icon==="string"?s.icon.slice(0,2):"S",channels:s.channels.filter(function(c){return c&&typeof c==="object"&&typeof c.id==="string"&&validName(c.name,30)&&(c.type==="text"||c.type==="voice")}).slice(0,MAX_CHANNELS).map(function(c){return {id:c.id.slice(0,100),name:c.name.trim().slice(0,30),type:c.type}})}})}if(!y.servers.length)y.servers=JSON.parse(JSON.stringify(base.servers));y.messages={};if(x.messages&&typeof x.messages==="object")Object.keys(x.messages).slice(0,MAX_SERVERS*MAX_CHANNELS).forEach(function(k){if(Array.isArray(x.messages[k]))y.messages[k]=x.messages[k].filter(function(m){return m&&typeof m==="object"&&typeof m.user==="string"&&typeof m.text==="string"}).slice(-MAX_MESSAGES_PER_CHANNEL).map(function(m){return {id:typeof m.id==="string"?m.id.slice(0,100):uid("m"),user:m.user.slice(0,24),text:m.text.slice(0,MAX_MESSAGE_LENGTH),time:typeof m.time==="number"?m.time:Date.now()}})});if(Array.isArray(x.friends))y.friends=x.friends.filter(function(v){return typeof v==="string"&&validName(v,24)}).slice(0,MAX_FRIENDS);if(Array.isArray(x.requests))y.requests=x.requests.filter(function(v){return typeof v==="string"&&validName(v,24)}).slice(0,MAX_REQUESTS);if(x.settings&&typeof x.settings==="object")y.settings={theme:x.settings.theme==="midnight"?"midnight":"dark",compact:!!x.settings.compact,animations:x.settings.animations!==false,notifications:x.settings.notifications!==false,keybinds:x.settings.keybinds!==false};return y}
function load(){try{return normalizeState(JSON.parse(localStorage.getItem(KEY)))}catch(e){return JSON.parse(JSON.stringify(base))}}
function save(){try{localStorage.setItem(KEY,JSON.stringify(state))}catch(e){toast("Local storage is full. Delete old data from Privacy settings.")}}
function uid(p){return (p||"id")+"-"+Date.now().toString(36)+"-"+Math.random().toString(36).slice(2,7)}
function esc(s){return String(s).replace(/[&<>"']/g,function(c){return {"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]})}
function init(){if(state.username){presence();render()}else{onboard()}}
function presence(){try{bc=new BroadcastChannel("revcord-local-v2:"+location.pathname);bc.onmessage=signal;bc.postMessage({type:"presence",from:state.username})}catch(e){}}
function server(){return state.servers.filter(function(s){return s.id===state.activeServer})[0]||state.servers[0]}
function chan(){return server().channels.filter(function(c){return c.id===state.activeChannel})[0]||server().channels[0]}
function av(n){return '<div class="avatar">'+esc((n||"?").trim().slice(0,2).toUpperCase())+'</div>'}
function toast(t){document.getElementById("toast").innerHTML='<div class="toast">'+esc(t)+'</div>';setTimeout(function(){document.getElementById("toast").innerHTML=""},2500)}
function onboard(){document.getElementById("root").innerHTML='<div style="height:100%;display:grid;place-items:center;padding:18px;background:radial-gradient(circle at 50% 20%,#252052,#0b0d12 55%)"><form id="join" style="width:min(430px,100%);background:#11141b;border:1px solid #252b37;border-radius:19px;padding:30px;box-shadow:0 25px 80px #000b"><div style="font-size:31px;font-weight:900">RevCord</div><p class="muted">A Discord-style web workspace with no fake users.</p><div class="notice">Your username, messages, servers and friends stay in this browser. Calling works between RevCord tabs/windows using WebRTC; cross-device accounts need a backend.</div><div class="field"><label>USERNAME</label><input id="username" required minlength="2" maxlength="24" autocomplete="off" placeholder="Choose a username"></div><button class="primary" style="width:100%">Enter RevCord</button></form></div>';document.getElementById("join").onsubmit=function(e){e.preventDefault();var n=document.getElementById("username").value.trim();if(n){state.username=n;save();presence();render()}}}
function render(){var s=server(),c=chan(),m=state.messages[c.id]||[];document.documentElement.style.setProperty("--a",state.settings.theme==="midnight"?"#2d9cff":"#6d5dfc");document.body.classList.toggle("compact",!!state.settings.compact);document.body.classList.toggle("noanim",!state.settings.animations);document.getElementById("root").innerHTML='<div class="app"><aside class="servers"><button class="server active">'+esc(s.icon)+'</button><div class="sep"></div>'+state.servers.filter(function(x){return x.id!=="home"}).map(function(x){return '<button class="server '+(x.id===s.id?"active":"")+'" data-server="'+x.id+'">'+esc(x.icon||x.name.slice(0,2))+'</button>'}).join("")+'<button class="server add" id="newServer">+</button></aside><aside class="side"><div class="head"><span>'+esc(s.name)+'</span><button id="serverSettings">⌄</button></div><div class="channels"><div class="cat"><span>Text channels</span><button class="icon" id="newText">+</button></div>'+s.channels.filter(function(x){return x.type==="text"}).map(channelButton).join("")+'<div class="cat"><span>Voice channels</span><button class="icon" id="newVoice">+</button></div>'+s.channels.filter(function(x){return x.type==="voice"}).map(channelButton).join("")+'</div><div class="profile">'+av(state.username)+'<div class="name">'+esc(state.username)+'<small>Local account</small></div><div class="actions"><button id="mute">♩</button><button id="deafen">◉</button><button id="settings">⚙</button></div></div></aside><main class="main"><div class="top"><b># '+esc(c.name)+'</b><span>• local workspace</span><div class="grow"></div><input class="search" id="search" placeholder="Search messages"><button class="icon" id="friends">♙</button><button class="icon" id="call">▣</button></div><div class="content"><section class="chat"><div class="messages" id="messages"><div class="welcome"><h1>Welcome to #'+esc(c.name)+'</h1><div class="muted">Messages are saved locally in this browser.</div></div>'+ (m.length?m.map(msg).join(""):'<div class="empty">No messages yet. Say hello.</div>')+'</div><div class="composer"><div class="box"><input id="compose" placeholder="Message #'+esc(c.name)+'"><button id="emoji">☺</button><button id="send">➤</button></div></div></section><aside class="members"><div class="mtitle">Members • 1</div><div class="member">'+av(state.username)+'<div><b>'+esc(state.username)+'</b><div class="online">● online</div></div></div></aside></div></main></div>';bind()}
function channelButton(x){return '<button class="chan '+(x.id===state.activeChannel?"active":"")+'" data-channel="'+x.id+'"><span class="hash">'+(x.type==="text"?"#":"◖")+'</span><span>'+esc(x.name)+'</span></button>'}
function msg(x){return '<div class="msg"><div class="av">'+av(x.user)+'</div><div><div class="meta"><b>'+esc(x.user)+'</b><time>'+new Date(x.time).toLocaleTimeString([], {hour:"numeric",minute:"2-digit"})+'</time></div><div class="msgtext">'+esc(x.text)+'</div></div></div>'}
function bind(){document.querySelectorAll("[data-server]").forEach(function(b){b.onclick=function(){if(voiceActive)leaveVoice();state.activeServer=b.dataset.server;state.activeChannel=server().channels[0].id;save();render()}});document.querySelectorAll("[data-channel]").forEach(function(b){b.onclick=function(){var selected=server().channels.filter(function(x){return x.id===b.dataset.channel})[0];if(voiceActive&&(!selected||selected.type!=="voice"||selected.id!==voiceRoom))leaveVoice();state.activeChannel=b.dataset.channel;save();render();if(selected&&selected.type==="voice")joinVoice(selected.id)}});document.getElementById("newServer").onclick=newServer;document.getElementById("newText").onclick=function(){newChannel("text")};document.getElementById("newVoice").onclick=function(){newChannel("voice")};document.getElementById("serverSettings").onclick=serverSettings;document.getElementById("settings").onclick=settings;document.getElementById("friends").onclick=friends;document.getElementById("call").onclick=function(){startCall("video")};document.getElementById("mute").onclick=mute;document.getElementById("deafen").onclick=deafen;var i=document.getElementById("compose");i.onkeydown=function(e){if(e.key==="Enter"){e.preventDefault();send()}};document.getElementById("send").onclick=send;document.getElementById("emoji").onclick=function(){i.value+=" 🙂";i.focus()};document.getElementById("search").oninput=function(){var q=this.value.toLowerCase();document.querySelectorAll(".msg").forEach(function(x){x.style.display=x.innerText.toLowerCase().indexOf(q)>=0?"flex":"none"})}}
function send(){var i=document.getElementById("compose"),t=i.value.trim();if(!t)return;if(t.length>MAX_MESSAGE_LENGTH){t=t.slice(0,MAX_MESSAGE_LENGTH);toast("Message truncated to "+MAX_MESSAGE_LENGTH+" characters")}var id=chan().id;if(!state.messages[id])state.messages[id]=[];state.messages[id].push({id:uid("m"),user:state.username,text:t,time:Date.now()});if(state.messages[id].length>MAX_MESSAGES_PER_CHANNEL)state.messages[id]=state.messages[id].slice(-MAX_MESSAGES_PER_CHANNEL);save();i.value="";render();var box=document.getElementById("messages");box.scrollTop=box.scrollHeight}
var modalOnClose=null;
function closeModal(runAction){var action=modalOnClose;modalOnClose=null;document.getElementById("modal").innerHTML="";if(runAction&&action)action()}
function modal(title,body,onClose){modalOnClose=onClose||null;document.getElementById("modal").innerHTML='<div class="back" id="back"><div class="modal"><div class="mh"><h2>'+title+'</h2><button class="icon" id="close">✕</button></div>'+body+'</div></div>';document.getElementById("close").onclick=function(){closeModal(true)};document.getElementById("back").onclick=function(e){if(e.target.id==="back")closeModal(true)}}
function newServer(){if(state.servers.length>=MAX_SERVERS)return toast("Maximum local servers reached");var n=prompt("Server name");if(!n||!n.trim())return;var s={id:uid("s"),name:n.trim().slice(0,30),icon:n.trim().slice(0,2).toUpperCase(),channels:[{id:uid("c"),name:"general",type:"text"},{id:uid("v"),name:"Lounge",type:"voice"}]};state.servers.push(s);state.activeServer=s.id;state.activeChannel=s.channels[0].id;state.messages[state.activeChannel]=[];save();render()}
function newChannel(type){if(server().channels.length>=MAX_CHANNELS)return toast("Maximum channels reached in this server");var n=prompt(type==="text"?"Text channel name":"Voice channel name");if(!n||!n.trim())return;var id=uid("c");server().channels.push({id:id,name:n.trim().slice(0,30),type:type});state.activeChannel=id;if(type==="text")state.messages[id]=[];save();render()}
function serverSettings(){modal("Server settings",'<div class="mb"><div class="field"><label>SERVER NAME</label><input id="sname" value="'+esc(server().name)+'"></div><button class="primary" id="saveS">Save</button> <button class="secondary danger" id="delS" '+(server().id==="home"?"disabled":"")+'>Delete server</button></div>');document.getElementById("saveS").onclick=function(){var n=document.getElementById("sname").value.trim();if(n)server().name=n;save();closeModal();render()};document.getElementById("delS").onclick=function(){if(server().id!=="home"&&confirm("Delete this local server?")){state.servers=state.servers.filter(function(x){return x.id!==server().id});state.activeServer="home";state.activeChannel="general";save();closeModal();render()}}}
function toggle(k){state.settings[k]=!state.settings[k];save();render();settings()}
function row(k,t,d){return '<div class="row"><div><b>'+t+'</b><p>'+d+'</p></div><button class="toggle '+(state.settings[k]?"on":"")+'" data-toggle="'+k+'"><i></i></button></div>'}
function settings(){modal("User settings",'<div class="tabs"><div class="tabbar"><button class="tab active" data-tab="profile">Profile</button><button class="tab" data-tab="appearance">Appearance</button><button class="tab" data-tab="keybinds">Keybinds</button><button class="tab" data-tab="privacy">Privacy</button></div><div class="mb" id="panel"></div></div>');var panel=document.getElementById("panel");function show(t){document.querySelectorAll("[data-tab]").forEach(function(x){x.classList.toggle("active",x.dataset.tab===t)});var h="";if(t==="profile")h='<h3>My profile</h3><div class="field"><label>DISPLAY NAME</label><input id="display" maxlength="24" value="'+esc(state.username)+'"></div><button class="primary" id="saveP">Save profile</button>';if(t==="appearance")h='<h3>Appearance</h3>'+row("compact","Compact layout","Tighter spacing")+row("animations","Animations","Keep interface transitions enabled")+'<div class="field" style="margin-top:18px"><label>THEME</label><select id="theme"><option value="dark">Dark</option><option value="midnight">Midnight</option></select></div>';if(t==="keybinds")h='<h3>Keybinds</h3><div class="row"><div><b>Quick switcher</b><p>Focus search</p></div><b>Ctrl K</b></div><div class="row"><div><b>Focus composer</b><p>Start typing</p></div><b>Ctrl /</b></div><div class="row"><div><b>Mute microphone</b><p>During a call</p></div><b>M</b></div>'+row("keybinds","Enable keybinds","Keyboard shortcuts control the UI");if(t==="privacy")h='<h3>Privacy & local data</h3><div class="notice">No backend is connected. Nothing in this frontend creates fake users or uploads your local workspace.</div>'+row("notifications","Notifications","Show local in-app notifications")+'<div class="row"><div><b>Reset local data</b><p>Delete this browser workspace</p></div><button class="secondary danger" id="reset">Reset</button></div>';panel.innerHTML=h;document.querySelectorAll("[data-toggle]").forEach(function(b){b.onclick=function(){toggle(b.dataset.toggle)}});if(document.getElementById("theme")){document.getElementById("theme").value=state.settings.theme;document.getElementById("theme").onchange=function(){state.settings.theme=this.value;save();render();settings()}}if(document.getElementById("saveP"))document.getElementById("saveP").onclick=function(){var n=document.getElementById("display").value.trim();if(n){state.username=n;save();closeModal();render()}};if(document.getElementById("reset"))document.getElementById("reset").onclick=function(){if(confirm("Reset all local RevCord data?")){localStorage.removeItem(KEY);location.reload()}}}document.querySelectorAll("[data-tab]").forEach(function(b){b.onclick=function(){show(b.dataset.tab)}});show("profile")}
function friends(){modal("Friends",'<div class="mb"><div class="notice">Friends are local-only for now. Open another RevCord tab with a different username to test requests. Cross-device friends need a backend.</div><div style="display:flex;gap:8px"><input id="friendName" maxlength="24" style="flex:1;background:var(--p2);border:1px solid var(--line);border-radius:8px;color:var(--text);padding:0 10px" placeholder="Username"><button class="primary" id="addFriend">Add</button></div><h3>Friends</h3><div id="flist">'+(state.friends.length?state.friends.map(function(f){return '<div class="friend">'+av(f)+'<div class="grow"><b>'+esc(f)+'</b><div class="pill">local friend</div></div><button class="icon" data-callfriend="'+esc(f)+'">▣</button></div>'}).join(""):'<div class="empty">No friends yet.</div>')+'</div><h3>Requests</h3><div>'+ (state.requests.length?state.requests.map(function(r){return '<div class="friend">'+av(r)+'<div class="grow"><b>'+esc(r)+'</b><div class="muted">Request</div></div><button class="primary" data-accept="'+esc(r)+'">Accept</button></div>'}).join(""):'<div class="empty">No pending requests.</div>')+'</div></div>');document.getElementById("addFriend").onclick=function(){requestFriend(document.getElementById("friendName").value.trim())};document.querySelectorAll("[data-accept]").forEach(function(b){b.onclick=function(){acceptFriend(b.dataset.accept)}});document.querySelectorAll("[data-callfriend]").forEach(function(b){b.onclick=function(){startCall("video",b.dataset.callfriend)}})}
function requestFriend(n){if(state.requests.length>=MAX_REQUESTS)return toast("Too many pending requests");if(!n||n===state.username)return toast("Enter another username");if(state.friends.indexOf(n)>=0)return toast("Already friends");try{bc.postMessage({type:"friend-request",from:state.username,to:n})}catch(e){}toast("Request sent to that username when they are open in another tab")}
function acceptFriend(n){if(state.friends.length>=MAX_FRIENDS)return toast("Friend limit reached");state.requests=state.requests.filter(function(x){return x!==n});if(state.friends.indexOf(n)<0)state.friends.push(n);save();try{bc.postMessage({type:"friend-accepted",from:state.username,to:n})}catch(e){}friends()}
async function startCall(mode,target){if(!navigator.mediaDevices||!window.RTCPeerConnection)return toast("This browser does not support WebRTC calling");if(!target)target=state.friends[0];if(!target)return toast("Add a friend first");if(voiceActive)leaveVoice();peer=target;callToken=uid("call");try{stream=await navigator.mediaDevices.getUserMedia({audio:true,video:mode==="video"})}catch(e){peer=null;callToken=null;return toast("Allow camera and microphone access to call")}showCall();pc=new RTCPeerConnection({iceServers:[{urls:"stun:stun.l.google.com:19302"}]});stream.getTracks().forEach(function(t){pc.addTrack(t,stream)});pc.onicecandidate=function(e){if(e.candidate)bc.postMessage({type:"offer-ice",from:state.username,to:peer,token:callToken,candidate:e.candidate})};pc.ontrack=function(e){var v=document.getElementById("remote");if(v)v.srcObject=e.streams[0]};pc.onconnectionstatechange=function(){if(pc&&pc.connectionState==="failed")toast("Call failed")};var offer=await pc.createOffer();await pc.setLocalDescription(offer);bc.postMessage({type:"offer",from:state.username,to:peer,token:callToken,offer:offer})}
function incomingCall(){modal("Incoming video call",'<div class="mb"><div class="notice">'+esc((incomingOffer&&incomingOffer.from)||"A user")+' is calling. Camera and microphone will not be accessed unless you accept.</div><button class="primary" id="acceptIncoming">Accept</button> <button class="secondary" id="declineIncoming">Decline</button></div>',function(){declineIncoming()});document.getElementById("acceptIncoming").onclick=acceptIncomingCall;document.getElementById("declineIncoming").onclick=declineIncoming}

function declineIncoming(){var d=incomingOffer;incomingOffer=null;try{if(d&&bc)bc.postMessage({type:"end",from:state.username,to:d.from,token:d.token})}catch(e){}closeModal()}
async function acceptIncomingCall(){var d=incomingOffer;if(!d)return;incomingOffer=null;peer=d.from;callToken=d.token;try{stream=await navigator.mediaDevices.getUserMedia({audio:true,video:true})}catch(e){peer=null;callToken=null;closeModal();return toast("Camera and microphone permission was not granted")}showCall();pc=new RTCPeerConnection({iceServers:[{urls:"stun:stun.l.google.com:19302"}]});stream.getTracks().forEach(function(t){pc.addTrack(t,stream)});pc.onicecandidate=function(e){if(e.candidate)bc.postMessage({type:"offer-ice",from:state.username,to:peer,token:callToken,candidate:e.candidate})};pc.ontrack=function(e){var v=document.getElementById("remote");if(v)v.srcObject=e.streams[0]};await pc.setRemoteDescription(d.offer);var a=await pc.createAnswer();await pc.setLocalDescription(a);bc.postMessage({type:"answer",from:state.username,to:peer,token:callToken,answer:a})}
function showCall(){modal("Video call",'<div class="call"><div class="videos"><div class="vid"><video id="local" autoplay muted playsinline></video><div class="label">You · '+esc(state.username)+'</div></div><div class="vid"><video id="remote" autoplay playsinline></video><div class="label">'+esc(peer)+'</div></div></div><div class="controls"><button id="cm">♩</button><button id="cv">▣</button><button class="end" id="ce">☎</button></div></div>',function(){endCall(true)});document.getElementById("local").srcObject=stream;document.getElementById("cm").onclick=mute;document.getElementById("cv").onclick=cam;document.getElementById("ce").onclick=function(){endCall(true)}}
async function signal(e){var d=e.data;if(!d||d.from===state.username||d.to&&d.to!==state.username)return;if(d.type==="friend-request"){if(state.requests.indexOf(d.from)<0&&state.requests.length<MAX_REQUESTS){state.requests.push(d.from);save();toast("Friend request from "+d.from)}}else if(d.type==="friend-accepted"){if(state.friends.indexOf(d.from)<0&&state.friends.length<MAX_FRIENDS){state.friends.push(d.from);save();toast(d.from+" accepted your request")}}else if(d.type==="offer"){if(voiceActive||pc||incomingOffer)return;incomingOffer=d;incomingCall()}else if(d.type==="answer"&&pc&&d.token===callToken){await pc.setRemoteDescription(d.answer)}else if(d.type==="offer-ice"&&pc&&d.token===callToken){try{await pc.addIceCandidate(d.candidate)}catch(e){}}else if(d.type==="end"&&d.token===callToken){endCall(false)}else if(d.type==="voice-join"){if(voiceActive&&d.room===voiceRoom&&d.from!==state.username){if(!voicePeers[d.from]){voicePeers[d.from]={};refreshVoiceRoom();createVoiceOffer(d.from)}}}else if(d.type==="voice-offer"&&voiceActive&&d.room===voiceRoom){await acceptVoiceOffer(d)}else if(d.type==="voice-answer"&&voiceActive&&d.room===voiceRoom){var p=voicePeers[d.from]&&voicePeers[d.from].pc;if(p)await p.setRemoteDescription(d.answer)}else if(d.type==="voice-ice"&&voiceActive&&d.room===voiceRoom){var q=voicePeers[d.from]&&voicePeers[d.from].pc;if(q)try{await q.addIceCandidate(d.candidate)}catch(e){}}else if(d.type==="voice-leave"&&voiceActive&&d.room===voiceRoom){removeVoicePeer(d.from)}}
function mute(){if(!stream)return toast("You are not in a call");var t=stream.getAudioTracks()[0];if(t)t.enabled=!t.enabled;var b=document.getElementById("cm")||document.getElementById("vmute")||document.getElementById("mute");if(b)b.classList.toggle("danger",t&&!t.enabled)}
function deafen(){if(voiceActive){deafened=!deafened;Object.keys(voicePeers).forEach(function(k){var a=document.getElementById("audio-"+k);if(a)a.muted=deafened});var vb=document.getElementById("vdeafen");if(vb)vb.classList.toggle("danger",deafened);return}var v=document.getElementById("remote");if(!v)return toast("You are not in a call");deafened=!deafened;v.muted=deafened;var b=document.getElementById("deafen");if(b)b.classList.toggle("danger",deafened)}
function cam(){if(!stream)return;var t=stream.getVideoTracks()[0];if(t)t.enabled=!t.enabled}
function endCall(notify){var oldPeer=peer,oldToken=callToken;try{stream&&stream.getTracks().forEach(function(t){t.stop()});pc&&pc.close();if(notify!==false&&bc&&oldPeer)bc.postMessage({type:"end",from:state.username,to:oldPeer,token:oldToken})}catch(e){}stream=null;pc=null;peer=null;callToken=null;incomingOffer=null;modalOnClose=null;closeModal(false)}
async function joinVoice(room){if(voiceActive)return;if(!navigator.mediaDevices||!window.RTCPeerConnection||!window.BroadcastChannel)return toast("This browser cannot start browser voice chat");voiceRoom=room;voiceActive=true;voicePeers={};try{stream=await navigator.mediaDevices.getUserMedia({audio:true,video:false})}catch(e){voiceActive=false;voiceRoom=null;return toast("Allow microphone access to join VC")}showVoiceRoom();bc.postMessage({type:"voice-join",from:state.username,room:voiceRoom})}
function showVoiceRoom(){var label=server().channels.filter(function(c){return c.id===voiceRoom})[0]?.name||voiceRoom;modal("Voice channel",'<div class="voice-room"><h3>◖ '+esc(label)+'</h3><div class="muted">Live browser voice chat</div><div class="voice-users" id="voiceUsers"></div><div class="controls"><button id="vmute">♩</button><button id="vdeafen">◉</button><button class="end" id="vleave">☎</button></div></div>',function(){leaveVoice()});document.getElementById("vleave").onclick=function(){leaveVoice()};document.getElementById("vmute").onclick=mute;document.getElementById("vdeafen").onclick=deafen;refreshVoiceRoom()}
function refreshVoiceRoom(){var box=document.getElementById("voiceUsers");if(!box)return;var names=[state.username].concat(Object.keys(voicePeers));box.innerHTML=names.map(function(n){return '<div class="voice-user">'+av(n)+'<b>'+esc(n)+'</b><span class="state">'+(n===state.username?"You":"Connected")+'</span></div>'}).join("")}
async function createVoiceOffer(name){if(voicePeers[name]&&voicePeers[name].pc)return;var entry=voicePeers[name]||{};var p=new RTCPeerConnection({iceServers:[{urls:"stun:stun.l.google.com:19302"}]});entry.pc=p;voicePeers[name]=entry;stream.getTracks().forEach(function(t){p.addTrack(t,stream)});p.onicecandidate=function(e){if(e.candidate)bc.postMessage({type:"voice-ice",from:state.username,to:name,room:voiceRoom,candidate:e.candidate})};p.ontrack=function(e){attachVoiceAudio(name,e.streams[0])};p.onconnectionstatechange=function(){if(["failed","closed","disconnected"].indexOf(p.connectionState)>=0)removeVoicePeer(name)};var o=await p.createOffer();await p.setLocalDescription(o);bc.postMessage({type:"voice-offer",from:state.username,to:name,room:voiceRoom,answerTo:name,offer:o})}
async function acceptVoiceOffer(d){var entry=voicePeers[d.from]||{};var p=new RTCPeerConnection({iceServers:[{urls:"stun:stun.l.google.com:19302"}]});entry.pc=p;voicePeers[d.from]=entry;stream.getTracks().forEach(function(t){p.addTrack(t,stream)});p.onicecandidate=function(e){if(e.candidate)bc.postMessage({type:"voice-ice",from:state.username,to:d.from,room:voiceRoom,candidate:e.candidate})};p.ontrack=function(e){attachVoiceAudio(d.from,e.streams[0])};p.onconnectionstatechange=function(){if(["failed","closed","disconnected"].indexOf(p.connectionState)>=0)removeVoicePeer(d.from)};await p.setRemoteDescription(d.offer);var a=await p.createAnswer();await p.setLocalDescription(a);bc.postMessage({type:"voice-answer",from:state.username,to:d.from,room:voiceRoom,answer:a})}
function attachVoiceAudio(name,media){var old=document.getElementById("audio-"+name);if(old)old.remove();var a=document.createElement("audio");a.id="audio-"+name;a.autoplay=true;a.playsInline=true;a.srcObject=media;a.muted=deafened;a.style.display="none";document.body.appendChild(a);a.play().catch(function(){toast("Click the page once if browser audio is blocked")})}
function removeVoicePeer(name){var e=voicePeers[name];if(e&&e.pc)e.pc.close();delete voicePeers[name];var a=document.getElementById("audio-"+name);if(a)a.remove();refreshVoiceRoom()}
function leaveVoice(){if(!voiceActive)return;try{bc.postMessage({type:"voice-leave",from:state.username,room:voiceRoom})}catch(e){}Object.keys(voicePeers).forEach(removeVoicePeer);if(stream){stream.getTracks().forEach(function(t){t.stop()});stream=null}voiceActive=false;voiceRoom=null;modalOnClose=null;closeModal(false);render()}

window.addEventListener("beforeunload",function(){try{if(voiceActive&&bc)bc.postMessage({type:"voice-leave",from:state.username,room:voiceRoom});if(peer&&callToken&&bc)bc.postMessage({type:"end",from:state.username,to:peer,token:callToken})}catch(e){}});

